# This is a basic workflow to help you get started with Actions

name: Build&Deploy

on: 
  push:
    tags:
      - v*

jobs:
  BuildAndRelease:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe Main
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: main.ahk
          out: wtils.exe
          icon: icons/wtils.ico

      - name: Set Setup version
        shell: pwsh
        run: |
          (Get-Content -path ./Setup.ahk -Raw) -replace '__VERSION__','${{github.ref_name}}' | Set-Content -Path ./Setup.ahk
      
      - name: Ahk2Exe Setup
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: Setup.ahk
          out: Setup.exe
          icon: icons/wtils.ico
      
      - name: Make Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
           wtils.exe
           Setup.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Make Winget release
      #   shell: pwsh
      #   run: |
      #     iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      #     .\wingetcreate.exe update perlt.wtils --submit -u https://github.com/Perlten/Wtils/releases/download/${{github.ref_name}}/Setup.exe -v ${{github.ref_name}} -t ${{secrets.WINGET_DEPLOY_PAT}}
